name: Publish Node Package to GitHub Packages

on:
  workflow_call:
    inputs:
      tag:
        description: "The tag to use"
        required: true
        type: string
      ref:
        description: "The ref to use"
        required: true
        type: string

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm run build
      - run: npm publish --tag ${{ inputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
