name: Create Release

on:
  workflow_dispatch:
    inputs:
      semverType:
        description: "Release Type"
        required: true
        default: "patch"
        type: choice
        options:
          - alpha
          - patch
          - minor
          - major

jobs:
  call_release:
    uses: ParadiseEngine/engine/.github/workflows/release.yml@alpha
    with:
      semverType: ${{ github.event.inputs.semverType }}
