name: Tag Version

on:
  workflow_call:
    inputs:
      semverType:
        description: "Release Type"
        required: true
        default: "patch"
        type: string
    outputs:
      version:
        value: ${{ jobs.version.outputs.version_output }}
      sha:
        value: ${{ jobs.version.outputs.sha_output }}

jobs:
  version:
    name: Bump Package Version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version_output: ${{ steps.version_command.outputs.version }}
      sha_output: ${{ steps.sha_command.outputs.sha }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com

      - if: ${{ inputs.semverType == 'alpha' }}
        run: echo "CUSTOM_NEXT_VERSION=$(npm version prerelease --preid=alpha)" >> $GITHUB_ENV
      - if: ${{ inputs.semverType == 'patch' }}
        run: echo "CUSTOM_NEXT_VERSION=$(npm version patch)" >> $GITHUB_ENV
      - if: ${{ inputs.semverType == 'minor' }}
        run: echo "CUSTOM_NEXT_VERSION=$(npm version minor)" >> $GITHUB_ENV
      - if: ${{ inputs.semverType == 'major' }}
        run: echo "CUSTOM_NEXT_VERSION=$(npm version major)" >> $GITHUB_ENV

      - run: git push --follow-tags
      - run: echo "CUSTOM_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - id: version_command
        run: echo "::set-output name=version::${CUSTOM_NEXT_VERSION}"
      - id: sha_command
        run: echo "::set-output name=sha::${CUSTOM_SHA}"
